name: Build distribution

on: [push, pull_request]

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install poetry
        run: |
            python -m pip install poetry

      - name: Install build dependencies
        run: python -m pip install build wheel twine

      - name: Build distributions
        shell: bash -l {0}
        run: |
          python -m poetry version $(git describe --tags --abbrev=0)
          python -m poetry build

      - name: Check build artifacts
        run: |
          python -m twine check --strict dist/*

      - name: Verify the built dist/wheel is valid
        if: github.event_name == 'push'
        run: |
          python -m pip install --upgrade pip
          python -m pip install dist/betfair_parser*.whl

      - name: Publish package to test pypi
        if: github.repository == 'limx0/betfair_parser' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.TESTPYPI_TOKEN }}
          repository-url: https://test.pypi.org/legacy/
          verbose: true

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: releases
          path: dist

  upload-pypi:
    needs: upload-test-pypi
    if: github.repository == 'limx0/betfair_parser' && github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: releases
          path: dist

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
